/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer } from 'ethers'
import { Provider, TransactionRequest } from '@ethersproject/providers'
import { Contract, ContractFactory, Overrides } from '@ethersproject/contracts'

import type { Helpers } from '../Helpers'

export class Helpers__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer)
  }

  deploy(overrides?: Overrides): Promise<Helpers> {
    return super.deploy(overrides || {}) as Promise<Helpers>
  }
  getDeployTransaction(overrides?: Overrides): TransactionRequest {
    return super.getDeployTransaction(overrides || {})
  }
  attach(address: string): Helpers {
    return super.attach(address) as Helpers
  }
  connect(signer: Signer): Helpers__factory {
    return super.connect(signer) as Helpers__factory
  }
  static connect(address: string, signerOrProvider: Signer | Provider): Helpers {
    return new Contract(address, _abi, signerOrProvider) as Helpers
  }
}

const _abi = [
  {
    inputs: [],
    name: 'connectorID',
    outputs: [
      {
        internalType: 'uint256',
        name: '_type',
        type: 'uint256',
      },
      {
        internalType: 'uint256',
        name: '_id',
        type: 'uint256',
      },
    ],
    stateMutability: 'pure',
    type: 'function',
  },
]

const _bytecode =
  '0x6080604052348015600f57600080fd5b50608a8061001e6000396000f3fe6080604052348015600f57600080fd5b506004361060285760003560e01c8063eb15f78114602d575b600080fd5b6033604c565b6040805192835260208301919091528051918290030190f35b60019060379056fea2646970667358221220c7a85ffcd42368e1a41dca7779198f37b77308bcca15eb591c9560c5c2433f8264736f6c63430007040033'
