/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from 'ethers'
import { Provider } from '@ethersproject/providers'

import type { IConnectKyber } from '../IConnectKyber'

export class IConnectKyber__factory {
  static connect(address: string, signerOrProvider: Signer | Provider): IConnectKyber {
    return new Contract(address, _abi, signerOrProvider) as IConnectKyber
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: 'address',
        name: 'buyAddr',
        type: 'address',
      },
      {
        internalType: 'address',
        name: 'sellAddr',
        type: 'address',
      },
      {
        internalType: 'uint256',
        name: 'sellAmt',
        type: 'uint256',
      },
      {
        internalType: 'uint256',
        name: 'unitAmt',
        type: 'uint256',
      },
      {
        internalType: 'uint256',
        name: 'getId',
        type: 'uint256',
      },
      {
        internalType: 'uint256',
        name: 'setId',
        type: 'uint256',
      },
    ],
    name: 'sell',
    outputs: [],
    stateMutability: 'payable',
    type: 'function',
  },
]
