/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from 'ethers'
import { Provider } from '@ethersproject/providers'

import type { IGelatoCondition } from '../IGelatoCondition'

export class IGelatoCondition__factory {
  static connect(address: string, signerOrProvider: Signer | Provider): IGelatoCondition {
    return new Contract(address, _abi, signerOrProvider) as IGelatoCondition
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: 'uint256',
        name: '_taskReceiptId',
        type: 'uint256',
      },
      {
        internalType: 'bytes',
        name: '_conditionData',
        type: 'bytes',
      },
      {
        internalType: 'uint256',
        name: '_cycleId',
        type: 'uint256',
      },
    ],
    name: 'ok',
    outputs: [
      {
        internalType: 'string',
        name: '',
        type: 'string',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
]
