/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from 'ethers'
import { Provider } from '@ethersproject/providers'

import type { IKyber } from '../IKyber'

export class IKyber__factory {
  static connect(address: string, signerOrProvider: Signer | Provider): IKyber {
    return new Contract(address, _abi, signerOrProvider) as IKyber
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: 'address',
        name: 'src',
        type: 'address',
      },
      {
        internalType: 'address',
        name: 'dest',
        type: 'address',
      },
      {
        internalType: 'uint256',
        name: 'srcQty',
        type: 'uint256',
      },
    ],
    name: 'getExpectedRate',
    outputs: [
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256',
      },
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: 'src',
        type: 'address',
      },
      {
        internalType: 'uint256',
        name: 'srcAmount',
        type: 'uint256',
      },
      {
        internalType: 'address',
        name: 'dest',
        type: 'address',
      },
      {
        internalType: 'address',
        name: 'destAddress',
        type: 'address',
      },
      {
        internalType: 'uint256',
        name: 'maxDestAmount',
        type: 'uint256',
      },
      {
        internalType: 'uint256',
        name: 'minConversionRate',
        type: 'uint256',
      },
      {
        internalType: 'address',
        name: 'walletId',
        type: 'address',
      },
    ],
    name: 'trade',
    outputs: [
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256',
      },
    ],
    stateMutability: 'payable',
    type: 'function',
  },
]
