/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from 'ethers'
import { Provider } from '@ethersproject/providers'

import type { ListInterface } from '../ListInterface'

export class ListInterface__factory {
  static connect(address: string, signerOrProvider: Signer | Provider): ListInterface {
    return new Contract(address, _abi, signerOrProvider) as ListInterface
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: 'address',
        name: '_account',
        type: 'address',
      },
    ],
    name: 'accountID',
    outputs: [
      {
        internalType: 'uint64',
        name: '',
        type: 'uint64',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
]
