/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers, EventFilter, Signer, BigNumber, BigNumberish, PopulatedTransaction } from 'ethers'
import { Contract, ContractTransaction, PayableOverrides, CallOverrides } from '@ethersproject/contracts'
import { BytesLike } from '@ethersproject/bytes'
import { Listener, Provider } from '@ethersproject/providers'
import { FunctionFragment, EventFragment, Result } from '@ethersproject/abi'

interface ConnectGelatoDataFullRefinanceMakerInterface extends ethers.utils.Interface {
  functions: {
    'connectorID()': FunctionFragment
    'getDataAndCastMakerToCompound(uint256,address)': FunctionFragment
    'getDataAndCastMakerToMaker(uint256,uint256,address,string)': FunctionFragment
    'name()': FunctionFragment
  }

  encodeFunctionData(functionFragment: 'connectorID', values?: undefined): string
  encodeFunctionData(functionFragment: 'getDataAndCastMakerToCompound', values: [BigNumberish, string]): string
  encodeFunctionData(
    functionFragment: 'getDataAndCastMakerToMaker',
    values: [BigNumberish, BigNumberish, string, string],
  ): string
  encodeFunctionData(functionFragment: 'name', values?: undefined): string

  decodeFunctionResult(functionFragment: 'connectorID', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'getDataAndCastMakerToCompound', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'getDataAndCastMakerToMaker', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'name', data: BytesLike): Result

  events: {}
}

export class ConnectGelatoDataFullRefinanceMaker extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this
  attach(addressOrName: string): this
  deployed(): Promise<this>

  on(event: EventFilter | string, listener: Listener): this
  once(event: EventFilter | string, listener: Listener): this
  addListener(eventName: EventFilter | string, listener: Listener): this
  removeAllListeners(eventName: EventFilter | string): this
  removeListener(eventName: any, listener: Listener): this

  interface: ConnectGelatoDataFullRefinanceMakerInterface

  functions: {
    connectorID(
      overrides?: CallOverrides,
    ): Promise<{
      _type: BigNumber
      id: BigNumber
      0: BigNumber
      1: BigNumber
    }>

    'connectorID()'(
      overrides?: CallOverrides,
    ): Promise<{
      _type: BigNumber
      id: BigNumber
      0: BigNumber
      1: BigNumber
    }>

    getDataAndCastMakerToCompound(
      _vaultId: BigNumberish,
      _colToken: string,
      overrides?: PayableOverrides,
    ): Promise<ContractTransaction>

    'getDataAndCastMakerToCompound(uint256,address)'(
      _vaultId: BigNumberish,
      _colToken: string,
      overrides?: PayableOverrides,
    ): Promise<ContractTransaction>

    getDataAndCastMakerToMaker(
      _vaultAId: BigNumberish,
      _vaultBId: BigNumberish,
      _colToken: string,
      _colType: string,
      overrides?: PayableOverrides,
    ): Promise<ContractTransaction>

    'getDataAndCastMakerToMaker(uint256,uint256,address,string)'(
      _vaultAId: BigNumberish,
      _vaultBId: BigNumberish,
      _colToken: string,
      _colType: string,
      overrides?: PayableOverrides,
    ): Promise<ContractTransaction>

    name(
      overrides?: CallOverrides,
    ): Promise<{
      0: string
    }>

    'name()'(
      overrides?: CallOverrides,
    ): Promise<{
      0: string
    }>
  }

  connectorID(
    overrides?: CallOverrides,
  ): Promise<{
    _type: BigNumber
    id: BigNumber
    0: BigNumber
    1: BigNumber
  }>

  'connectorID()'(
    overrides?: CallOverrides,
  ): Promise<{
    _type: BigNumber
    id: BigNumber
    0: BigNumber
    1: BigNumber
  }>

  getDataAndCastMakerToCompound(
    _vaultId: BigNumberish,
    _colToken: string,
    overrides?: PayableOverrides,
  ): Promise<ContractTransaction>

  'getDataAndCastMakerToCompound(uint256,address)'(
    _vaultId: BigNumberish,
    _colToken: string,
    overrides?: PayableOverrides,
  ): Promise<ContractTransaction>

  getDataAndCastMakerToMaker(
    _vaultAId: BigNumberish,
    _vaultBId: BigNumberish,
    _colToken: string,
    _colType: string,
    overrides?: PayableOverrides,
  ): Promise<ContractTransaction>

  'getDataAndCastMakerToMaker(uint256,uint256,address,string)'(
    _vaultAId: BigNumberish,
    _vaultBId: BigNumberish,
    _colToken: string,
    _colType: string,
    overrides?: PayableOverrides,
  ): Promise<ContractTransaction>

  name(overrides?: CallOverrides): Promise<string>

  'name()'(overrides?: CallOverrides): Promise<string>

  callStatic: {
    connectorID(
      overrides?: CallOverrides,
    ): Promise<{
      _type: BigNumber
      id: BigNumber
      0: BigNumber
      1: BigNumber
    }>

    'connectorID()'(
      overrides?: CallOverrides,
    ): Promise<{
      _type: BigNumber
      id: BigNumber
      0: BigNumber
      1: BigNumber
    }>

    getDataAndCastMakerToCompound(_vaultId: BigNumberish, _colToken: string, overrides?: CallOverrides): Promise<void>

    'getDataAndCastMakerToCompound(uint256,address)'(
      _vaultId: BigNumberish,
      _colToken: string,
      overrides?: CallOverrides,
    ): Promise<void>

    getDataAndCastMakerToMaker(
      _vaultAId: BigNumberish,
      _vaultBId: BigNumberish,
      _colToken: string,
      _colType: string,
      overrides?: CallOverrides,
    ): Promise<void>

    'getDataAndCastMakerToMaker(uint256,uint256,address,string)'(
      _vaultAId: BigNumberish,
      _vaultBId: BigNumberish,
      _colToken: string,
      _colType: string,
      overrides?: CallOverrides,
    ): Promise<void>

    name(overrides?: CallOverrides): Promise<string>

    'name()'(overrides?: CallOverrides): Promise<string>
  }

  filters: {}

  estimateGas: {
    connectorID(overrides?: CallOverrides): Promise<BigNumber>

    'connectorID()'(overrides?: CallOverrides): Promise<BigNumber>

    getDataAndCastMakerToCompound(
      _vaultId: BigNumberish,
      _colToken: string,
      overrides?: PayableOverrides,
    ): Promise<BigNumber>

    'getDataAndCastMakerToCompound(uint256,address)'(
      _vaultId: BigNumberish,
      _colToken: string,
      overrides?: PayableOverrides,
    ): Promise<BigNumber>

    getDataAndCastMakerToMaker(
      _vaultAId: BigNumberish,
      _vaultBId: BigNumberish,
      _colToken: string,
      _colType: string,
      overrides?: PayableOverrides,
    ): Promise<BigNumber>

    'getDataAndCastMakerToMaker(uint256,uint256,address,string)'(
      _vaultAId: BigNumberish,
      _vaultBId: BigNumberish,
      _colToken: string,
      _colType: string,
      overrides?: PayableOverrides,
    ): Promise<BigNumber>

    name(overrides?: CallOverrides): Promise<BigNumber>

    'name()'(overrides?: CallOverrides): Promise<BigNumber>
  }

  populateTransaction: {
    connectorID(overrides?: CallOverrides): Promise<PopulatedTransaction>

    'connectorID()'(overrides?: CallOverrides): Promise<PopulatedTransaction>

    getDataAndCastMakerToCompound(
      _vaultId: BigNumberish,
      _colToken: string,
      overrides?: PayableOverrides,
    ): Promise<PopulatedTransaction>

    'getDataAndCastMakerToCompound(uint256,address)'(
      _vaultId: BigNumberish,
      _colToken: string,
      overrides?: PayableOverrides,
    ): Promise<PopulatedTransaction>

    getDataAndCastMakerToMaker(
      _vaultAId: BigNumberish,
      _vaultBId: BigNumberish,
      _colToken: string,
      _colType: string,
      overrides?: PayableOverrides,
    ): Promise<PopulatedTransaction>

    'getDataAndCastMakerToMaker(uint256,uint256,address,string)'(
      _vaultAId: BigNumberish,
      _vaultBId: BigNumberish,
      _colToken: string,
      _colType: string,
      overrides?: PayableOverrides,
    ): Promise<PopulatedTransaction>

    name(overrides?: CallOverrides): Promise<PopulatedTransaction>

    'name()'(overrides?: CallOverrides): Promise<PopulatedTransaction>
  }
}
