/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers, EventFilter, Signer, BigNumber, BigNumberish, PopulatedTransaction } from 'ethers'
import { Contract, ContractTransaction, PayableOverrides, CallOverrides } from '@ethersproject/contracts'
import { BytesLike } from '@ethersproject/bytes'
import { Listener, Provider } from '@ethersproject/providers'
import { FunctionFragment, EventFragment, Result } from '@ethersproject/abi'

interface IConnectKyberInterface extends ethers.utils.Interface {
  functions: {
    'sell(address,address,uint256,uint256,uint256,uint256)': FunctionFragment
  }

  encodeFunctionData(
    functionFragment: 'sell',
    values: [string, string, BigNumberish, BigNumberish, BigNumberish, BigNumberish],
  ): string

  decodeFunctionResult(functionFragment: 'sell', data: BytesLike): Result

  events: {}
}

export class IConnectKyber extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this
  attach(addressOrName: string): this
  deployed(): Promise<this>

  on(event: EventFilter | string, listener: Listener): this
  once(event: EventFilter | string, listener: Listener): this
  addListener(eventName: EventFilter | string, listener: Listener): this
  removeAllListeners(eventName: EventFilter | string): this
  removeListener(eventName: any, listener: Listener): this

  interface: IConnectKyberInterface

  functions: {
    sell(
      buyAddr: string,
      sellAddr: string,
      sellAmt: BigNumberish,
      unitAmt: BigNumberish,
      getId: BigNumberish,
      setId: BigNumberish,
      overrides?: PayableOverrides,
    ): Promise<ContractTransaction>

    'sell(address,address,uint256,uint256,uint256,uint256)'(
      buyAddr: string,
      sellAddr: string,
      sellAmt: BigNumberish,
      unitAmt: BigNumberish,
      getId: BigNumberish,
      setId: BigNumberish,
      overrides?: PayableOverrides,
    ): Promise<ContractTransaction>
  }

  sell(
    buyAddr: string,
    sellAddr: string,
    sellAmt: BigNumberish,
    unitAmt: BigNumberish,
    getId: BigNumberish,
    setId: BigNumberish,
    overrides?: PayableOverrides,
  ): Promise<ContractTransaction>

  'sell(address,address,uint256,uint256,uint256,uint256)'(
    buyAddr: string,
    sellAddr: string,
    sellAmt: BigNumberish,
    unitAmt: BigNumberish,
    getId: BigNumberish,
    setId: BigNumberish,
    overrides?: PayableOverrides,
  ): Promise<ContractTransaction>

  callStatic: {
    sell(
      buyAddr: string,
      sellAddr: string,
      sellAmt: BigNumberish,
      unitAmt: BigNumberish,
      getId: BigNumberish,
      setId: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<void>

    'sell(address,address,uint256,uint256,uint256,uint256)'(
      buyAddr: string,
      sellAddr: string,
      sellAmt: BigNumberish,
      unitAmt: BigNumberish,
      getId: BigNumberish,
      setId: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<void>
  }

  filters: {}

  estimateGas: {
    sell(
      buyAddr: string,
      sellAddr: string,
      sellAmt: BigNumberish,
      unitAmt: BigNumberish,
      getId: BigNumberish,
      setId: BigNumberish,
      overrides?: PayableOverrides,
    ): Promise<BigNumber>

    'sell(address,address,uint256,uint256,uint256,uint256)'(
      buyAddr: string,
      sellAddr: string,
      sellAmt: BigNumberish,
      unitAmt: BigNumberish,
      getId: BigNumberish,
      setId: BigNumberish,
      overrides?: PayableOverrides,
    ): Promise<BigNumber>
  }

  populateTransaction: {
    sell(
      buyAddr: string,
      sellAddr: string,
      sellAmt: BigNumberish,
      unitAmt: BigNumberish,
      getId: BigNumberish,
      setId: BigNumberish,
      overrides?: PayableOverrides,
    ): Promise<PopulatedTransaction>

    'sell(address,address,uint256,uint256,uint256,uint256)'(
      buyAddr: string,
      sellAddr: string,
      sellAmt: BigNumberish,
      unitAmt: BigNumberish,
      getId: BigNumberish,
      setId: BigNumberish,
      overrides?: PayableOverrides,
    ): Promise<PopulatedTransaction>
  }
}
