/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers, EventFilter, Signer, BigNumber, BigNumberish, PopulatedTransaction } from 'ethers'
import { Contract, ContractTransaction, CallOverrides } from '@ethersproject/contracts'
import { BytesLike } from '@ethersproject/bytes'
import { Listener, Provider } from '@ethersproject/providers'
import { FunctionFragment, EventFragment, Result } from '@ethersproject/abi'

interface ListInterfaceInterface extends ethers.utils.Interface {
  functions: {
    'accountID(address)': FunctionFragment
  }

  encodeFunctionData(functionFragment: 'accountID', values: [string]): string

  decodeFunctionResult(functionFragment: 'accountID', data: BytesLike): Result

  events: {}
}

export class ListInterface extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this
  attach(addressOrName: string): this
  deployed(): Promise<this>

  on(event: EventFilter | string, listener: Listener): this
  once(event: EventFilter | string, listener: Listener): this
  addListener(eventName: EventFilter | string, listener: Listener): this
  removeAllListeners(eventName: EventFilter | string): this
  removeListener(eventName: any, listener: Listener): this

  interface: ListInterfaceInterface

  functions: {
    accountID(
      _account: string,
      overrides?: CallOverrides,
    ): Promise<{
      0: BigNumber
    }>

    'accountID(address)'(
      _account: string,
      overrides?: CallOverrides,
    ): Promise<{
      0: BigNumber
    }>
  }

  accountID(_account: string, overrides?: CallOverrides): Promise<BigNumber>

  'accountID(address)'(_account: string, overrides?: CallOverrides): Promise<BigNumber>

  callStatic: {
    accountID(_account: string, overrides?: CallOverrides): Promise<BigNumber>

    'accountID(address)'(_account: string, overrides?: CallOverrides): Promise<BigNumber>
  }

  filters: {}

  estimateGas: {
    accountID(_account: string, overrides?: CallOverrides): Promise<BigNumber>

    'accountID(address)'(_account: string, overrides?: CallOverrides): Promise<BigNumber>
  }

  populateTransaction: {
    accountID(_account: string, overrides?: CallOverrides): Promise<PopulatedTransaction>

    'accountID(address)'(_account: string, overrides?: CallOverrides): Promise<PopulatedTransaction>
  }
}
