/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers, EventFilter, Signer, BigNumber, BigNumberish, PopulatedTransaction } from 'ethers'
import { Contract, ContractTransaction, CallOverrides } from '@ethersproject/contracts'
import { BytesLike } from '@ethersproject/bytes'
import { Listener, Provider } from '@ethersproject/providers'
import { FunctionFragment, EventFragment, Result } from '@ethersproject/abi'

interface MakerResolverInterface extends ethers.utils.Interface {
  functions: {
    'getMakerVaulsssstDebt(uint256)': FunctionFragment
    'getMakerVaultCosssllateralBalance(uint256)': FunctionFragment
    'getMakerVaultsssRawDebt(uint256)': FunctionFragment
  }

  encodeFunctionData(functionFragment: 'getMakerVaulsssstDebt', values: [BigNumberish]): string
  encodeFunctionData(functionFragment: 'getMakerVaultCosssllateralBalance', values: [BigNumberish]): string
  encodeFunctionData(functionFragment: 'getMakerVaultsssRawDebt', values: [BigNumberish]): string

  decodeFunctionResult(functionFragment: 'getMakerVaulsssstDebt', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'getMakerVaultCosssllateralBalance', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'getMakerVaultsssRawDebt', data: BytesLike): Result

  events: {}
}

export class MakerResolver extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this
  attach(addressOrName: string): this
  deployed(): Promise<this>

  on(event: EventFilter | string, listener: Listener): this
  once(event: EventFilter | string, listener: Listener): this
  addListener(eventName: EventFilter | string, listener: Listener): this
  removeAllListeners(eventName: EventFilter | string): this
  removeListener(eventName: any, listener: Listener): this

  interface: MakerResolverInterface

  functions: {
    getMakerVaulsssstDebt(
      _vaultId: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<{
      0: BigNumber
    }>

    'getMakerVaulsssstDebt(uint256)'(
      _vaultId: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<{
      0: BigNumber
    }>

    getMakerVaultCosssllateralBalance(
      _vaultId: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<{
      0: BigNumber
    }>

    'getMakerVaultCosssllateralBalance(uint256)'(
      _vaultId: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<{
      0: BigNumber
    }>

    getMakerVaultsssRawDebt(
      _vaultId: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<{
      0: BigNumber
    }>

    'getMakerVaultsssRawDebt(uint256)'(
      _vaultId: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<{
      0: BigNumber
    }>
  }

  getMakerVaulsssstDebt(_vaultId: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>

  'getMakerVaulsssstDebt(uint256)'(_vaultId: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>

  getMakerVaultCosssllateralBalance(_vaultId: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>

  'getMakerVaultCosssllateralBalance(uint256)'(_vaultId: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>

  getMakerVaultsssRawDebt(_vaultId: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>

  'getMakerVaultsssRawDebt(uint256)'(_vaultId: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>

  callStatic: {
    getMakerVaulsssstDebt(_vaultId: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>

    'getMakerVaulsssstDebt(uint256)'(_vaultId: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>

    getMakerVaultCosssllateralBalance(_vaultId: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>

    'getMakerVaultCosssllateralBalance(uint256)'(_vaultId: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>

    getMakerVaultsssRawDebt(_vaultId: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>

    'getMakerVaultsssRawDebt(uint256)'(_vaultId: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>
  }

  filters: {}

  estimateGas: {
    getMakerVaulsssstDebt(_vaultId: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>

    'getMakerVaulsssstDebt(uint256)'(_vaultId: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>

    getMakerVaultCosssllateralBalance(_vaultId: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>

    'getMakerVaultCosssllateralBalance(uint256)'(_vaultId: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>

    getMakerVaultsssRawDebt(_vaultId: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>

    'getMakerVaultsssRawDebt(uint256)'(_vaultId: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>
  }

  populateTransaction: {
    getMakerVaulsssstDebt(_vaultId: BigNumberish, overrides?: CallOverrides): Promise<PopulatedTransaction>

    'getMakerVaulsssstDebt(uint256)'(_vaultId: BigNumberish, overrides?: CallOverrides): Promise<PopulatedTransaction>

    getMakerVaultCosssllateralBalance(_vaultId: BigNumberish, overrides?: CallOverrides): Promise<PopulatedTransaction>

    'getMakerVaultCosssllateralBalance(uint256)'(
      _vaultId: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>

    getMakerVaultsssRawDebt(_vaultId: BigNumberish, overrides?: CallOverrides): Promise<PopulatedTransaction>

    'getMakerVaultsssRawDebt(uint256)'(_vaultId: BigNumberish, overrides?: CallOverrides): Promise<PopulatedTransaction>
  }
}
